name: Deploy Java Application

on:
  push:
      branches:
      - 'main'
      paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run online Script
        run: |
            echo "Running online script"

  docker:
    uses: EaseCloudStudio/java-workflow-actions/.github/workflows/buid_container.yaml@main
    with:
      aws-region: "us-east-2"
      image-name: "java-demo"